name: continuous deployment

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install dependencies
        run: |
          npm cache clean --force
      - name: push /out/ to gh-pages
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git --work-tree out add --all
          git commit -m "Automatic deployment by github-actions"
          git push origin HEAD:gh-pages --force
